// SPDX-License-Identifier: GPL-2.0
/*
 * Xilinx HLS Test Pattern Generator
 *
 * TPG v8 is a complete redesign of the Xilinx Test Pattern Generator IP using
 * Vivado HLS. It is programmed through the AXI4-Lite register interface
 * generated by the HLS tool, which is incompatible with the register interface
 * of the older TPG versions handled by the xilinx-tpg driver.
 *
 * Copyright (C) 2013-2015 Ideas on Board
 * Copyright (C) 2013-2015 Xilinx, Inc.
 *
 * Contacts: Hyun Kwon <hyun.kwon@xilinx.com>
 *           Laurent Pinchart <laurent.pinchart@ideasonboard.com>
 */

#include <linux/bitops.h>
#include <linux/clk.h>
#include <linux/device.h>
#include <linux/gpio/consumer.h>
#include <linux/io.h>
#include <linux/module.h>
#include <linux/of.h>
#include <linux/of_graph.h>
#include <linux/platform_device.h>
#include <linux/pm.h>
#include <linux/property.h>
#include <linux/xilinx-v4l2-controls.h>

#include <media/v4l2-async.h>
#include <media/v4l2-ctrls.h>
#include <media/v4l2-mc.h>
#include <media/v4l2-subdev.h>

#include "xilinx-vtc.h"

/*
 * Registers 0x0000 to 0x0018 implement the standard block control interface
 * generated by Vivado HLS, the other registers are specific to the TPG.
 */
#define XTPG_HLS_CTRL				0x0000
#define XTPG_HLS_CTRL_AP_START			BIT(0)
#define XTPG_HLS_CTRL_AUTO_RESTART		BIT(7)
#define XTPG_HLS_ROWS				0x0010
#define XTPG_HLS_COLS				0x0018
#define XTPG_HLS_BG_PATTERN			0x0020
#define XTPG_HLS_FG_PATTERN			0x0028
#define XTPG_HLS_MASK_ID			0x0030
#define XTPG_HLS_MOTION_SPEED			0x0038
#define XTPG_HLS_COLOR_FORMAT			0x0040
#define XTPG_HLS_COLOR_FORMAT_RGB		0
#define XTPG_HLS_COLOR_FORMAT_YUV_444		1
#define XTPG_HLS_COLOR_FORMAT_YUV_422		2
#define XTPG_HLS_COLOR_FORMAT_YUV_420		3
#define XTPG_HLS_CROSS_HAIR_HOR			0x0048
#define XTPG_HLS_CROSS_HAIR_VER			0x0050
#define XTPG_HLS_ZPLATE_HOR_CNTL_START		0x0058
#define XTPG_HLS_ZPLATE_HOR_CNTL_DELTA		0x0060
#define XTPG_HLS_ZPLATE_VER_CNTL_START		0x0068
#define XTPG_HLS_ZPLATE_VER_CNTL_DELTA		0x0070
#define XTPG_HLS_BOX_SIZE			0x0078
#define XTPG_HLS_BOX_COLOR_RED_CB		0x0080
#define XTPG_HLS_BOX_COLOR_GREEN_CR		0x0088
#define XTPG_HLS_BOX_COLOR_BLUE_Y		0x0090
#define XTPG_HLS_ENABLE_INPUT			0x0098
#define XTPG_HLS_USE_INPUT_VID_STREAM		BIT(0)

#define XTPG_MIN_WIDTH				64
#define XTPG_DEF_WIDTH				1920
#define XTPG_MAX_WIDTH				10328
#define XTPG_MIN_HEIGHT				64
#define XTPG_DEF_HEIGHT				1080
#define XTPG_MAX_HEIGHT				7760

/*
 * The minimum blanking value is one clock cycle for the front porch, one clock
 * cycle for the sync pulse and one clock cycle for the back porch.
 */
#define XTPG_MIN_HBLANK				3
#define XTPG_MAX_HBLANK				(XVTC_MAX_HSIZE - XTPG_MIN_WIDTH)
#define XTPG_MIN_VBLANK				3
#define XTPG_MAX_VBLANK				(XVTC_MAX_VSIZE - XTPG_MIN_HEIGHT)

#define XTPG_DEF_PPC				1

/**
 * struct xtpg_format - Media bus format supported by the TPG
 * @code: media bus format code
 * @color_format: corresponding value of the XTPG_HLS_COLOR_FORMAT register
 */
struct xtpg_format {
	u32 code;
	u32 color_format;
};

static const struct xtpg_format xtpg_formats[] = {
	{ MEDIA_BUS_FMT_RBG888_1X24, XTPG_HLS_COLOR_FORMAT_RGB },
	{ MEDIA_BUS_FMT_VUY8_1X24, XTPG_HLS_COLOR_FORMAT_YUV_444 },
	{ MEDIA_BUS_FMT_VYUY8_1X16, XTPG_HLS_COLOR_FORMAT_YUV_422 },
	{ MEDIA_BUS_FMT_UYVY10_1X20, XTPG_HLS_COLOR_FORMAT_YUV_422 },
};

/**
 * struct xtpg_device - Xilinx HLS Test Pattern Generator device structure
 * @subdev: V4L2 subdevice
 * @notifier: Async notifier for the upstream subdev
 * @dev: (OF) device
 * @iomem: device I/O register space remapped to kernel virtual memory
 * @clk: video core clock
 * @saved_ctrl: saved control register for resume / suspend
 * @pads: media pads
 * @npads: number of pads (1 or 2)
 * @has_input: whether an input is connected to the sink pad
 * @default_format: default V4L2 media bus format
 * @ctrl_handler: control handler
 * @hblank: horizontal blanking control
 * @vblank: vertical blanking control
 * @pattern: test pattern control
 * @vtc: video timing controller
 * @vtmux_gpio: video timing mux GPIO
 * @rst_gpio: reset IP core GPIO
 * @max_width: maximum width supported by this instance
 * @max_height: maximum height supported by this instance
 * @ppc: pixels per clock processed by this instance
 */
struct xtpg_device {
	struct v4l2_subdev subdev;
	struct v4l2_async_notifier notifier;
	struct device *dev;
	void __iomem *iomem;
	struct clk *clk;
	u32 saved_ctrl;

	struct media_pad pads[2];
	unsigned int npads;
	bool has_input;

	struct v4l2_mbus_framefmt default_format;

	struct v4l2_ctrl_handler ctrl_handler;
	struct v4l2_ctrl *hblank;
	struct v4l2_ctrl *vblank;
	struct v4l2_ctrl *pattern;

	struct xvtc_device *vtc;
	struct gpio_desc *vtmux_gpio;
	struct gpio_desc *rst_gpio;

	u32 max_width;
	u32 max_height;
	u32 ppc;
};

static inline struct xtpg_device *to_tpg(struct v4l2_subdev *subdev)
{
	return container_of(subdev, struct xtpg_device, subdev);
}

static const struct xtpg_format *xtpg_get_format(u32 code)
{
	unsigned int i;

	for (i = 0; i < ARRAY_SIZE(xtpg_formats); ++i) {
		if (xtpg_formats[i].code == code)
			return &xtpg_formats[i];
	}

	return NULL;
}

/* -----------------------------------------------------------------------------
 * Register Access
 */

static inline u32 xtpg_read(struct xtpg_device *xtpg, u32 addr)
{
	return ioread32(xtpg->iomem + addr);
}

static inline void xtpg_write(struct xtpg_device *xtpg, u32 addr, u32 value)
{
	iowrite32(value, xtpg->iomem + addr);
}

static inline void xtpg_set(struct xtpg_device *xtpg, u32 addr, u32 set)
{
	xtpg_write(xtpg, addr, xtpg_read(xtpg, addr) | set);
}

/*
 * The HLS block runs one frame per ap_start pulse. Setting the auto-restart bit
 * makes the block restart on its own, and clearing it stops the block after the
 * frame being processed.
 */
static inline void xtpg_start(struct xtpg_device *xtpg)
{
	xtpg_write(xtpg, XTPG_HLS_CTRL,
		   XTPG_HLS_CTRL_AUTO_RESTART | XTPG_HLS_CTRL_AP_START);
}

static inline void xtpg_stop(struct xtpg_device *xtpg)
{
	xtpg_write(xtpg, XTPG_HLS_CTRL, 0);
}

static void xtpg_config_vtc(struct xtpg_device *xtpg,
			    const struct v4l2_mbus_framefmt *format)
{
	struct xvtc_config config = {
		.hblank_start = format->width / xtpg->ppc,
		.hsync_start = format->width / xtpg->ppc + 1,
		.vblank_start = format->height,
		.vsync_start = format->height + 1,
	};
	unsigned int htotal;
	unsigned int vtotal;

	htotal = min_t(unsigned int, XVTC_MAX_HSIZE,
		       (xtpg->hblank->cur.val + format->width) / xtpg->ppc);
	vtotal = min_t(unsigned int, XVTC_MAX_VSIZE,
		       xtpg->vblank->cur.val + format->height);

	config.hsync_end = htotal - 1;
	config.hsize = htotal;
	config.vsync_end = vtotal - 1;
	config.vsize = vtotal;

	xvtc_generator_start(xtpg->vtc, &config);
}

static void __xtpg_update_pattern_control(struct xtpg_device *xtpg,
					  bool passthrough, bool pattern)
{
	u32 pattern_mask = (1 << (xtpg->pattern->maximum + 1)) - 1;

	/*
	 * If the TPG has no sink pad or no input connected to its sink pad
	 * passthrough mode can't be enabled.
	 */
	if (xtpg->npads == 1 || !xtpg->has_input)
		passthrough = false;

	/* If passthrough mode is allowed unmask bit 0. */
	if (passthrough)
		pattern_mask &= ~1;

	/* If test pattern mode is allowed unmask all other bits. */
	if (pattern)
		pattern_mask &= 1;

	__v4l2_ctrl_modify_range(xtpg->pattern, 0, xtpg->pattern->maximum,
				 pattern_mask, pattern ? 9 : 0);
}

static void xtpg_update_pattern_control(struct xtpg_device *xtpg,
					bool passthrough, bool pattern)
{
	mutex_lock(xtpg->ctrl_handler.lock);
	__xtpg_update_pattern_control(xtpg, passthrough, pattern);
	mutex_unlock(xtpg->ctrl_handler.lock);
}

/* -----------------------------------------------------------------------------
 * V4L2 Subdevice Video Operations
 */

static int xtpg_set_remote_stream(struct xtpg_device *xtpg, bool enable)
{
	struct media_pad *remote;
	struct v4l2_subdev *subdev;
	int ret;

	if (xtpg->npads == 1)
		return 0;

	remote = media_pad_remote_pad_first(&xtpg->pads[0]);
	if (!remote || !is_media_entity_v4l2_subdev(remote->entity))
		return 0;

	subdev = media_entity_to_v4l2_subdev(remote->entity);

	if (enable)
		ret = v4l2_subdev_enable_streams(subdev, remote->index,
						 BIT_ULL(0));
	else
		ret = v4l2_subdev_disable_streams(subdev, remote->index,
						  BIT_ULL(0));

	if (ret < 0 && ret != -ENOIOCTLCMD)
		return ret;

	return 0;
}

static int xtpg_enable_streams(struct v4l2_subdev *subdev,
			       struct v4l2_subdev_state *state,
			       u32 pad, u64 streams_mask)
{
	struct xtpg_device *xtpg = to_tpg(subdev);
	const struct v4l2_mbus_framefmt *format;
	const struct xtpg_format *info;
	bool passthrough;
	int ret;

	format = v4l2_subdev_state_get_format(state, 0);

	info = xtpg_get_format(format->code);
	if (!info)
		return -EINVAL;

	xtpg_write(xtpg, XTPG_HLS_COLOR_FORMAT, info->color_format);
	xtpg_write(xtpg, XTPG_HLS_COLS, format->width);
	xtpg_write(xtpg, XTPG_HLS_ROWS, format->height);

	if (xtpg->vtc)
		xtpg_config_vtc(xtpg, format);

	xtpg_write(xtpg, XTPG_HLS_BG_PATTERN, xtpg->pattern->cur.val);

	/*
	 * Switching between passthrough and test pattern generation modes isn't
	 * allowed during streaming, update the control range accordingly.
	 */
	passthrough = xtpg->pattern->cur.val == 0;
	__xtpg_update_pattern_control(xtpg, passthrough, !passthrough);

	if (xtpg->vtmux_gpio)
		gpiod_set_value_cansleep(xtpg->vtmux_gpio, !passthrough);

	xtpg_set(xtpg, XTPG_HLS_ENABLE_INPUT, XTPG_HLS_USE_INPUT_VID_STREAM);
	xtpg_start(xtpg);

	ret = xtpg_set_remote_stream(xtpg, true);
	if (ret) {
		xtpg_stop(xtpg);
		if (xtpg->vtc)
			xvtc_generator_stop(xtpg->vtc);

		__xtpg_update_pattern_control(xtpg, true, true);

		return ret;
	}

	return 0;
}

static int xtpg_disable_streams(struct v4l2_subdev *subdev,
				struct v4l2_subdev_state *state,
				u32 pad, u64 streams_mask)
{
	struct xtpg_device *xtpg = to_tpg(subdev);

	xtpg_set_remote_stream(xtpg, false);

	xtpg_stop(xtpg);
	if (xtpg->vtc)
		xvtc_generator_stop(xtpg->vtc);

	__xtpg_update_pattern_control(xtpg, true, true);

	return 0;
}

/* -----------------------------------------------------------------------------
 * V4L2 Subdevice Pad Operations
 */

static int xtpg_enum_mbus_code(struct v4l2_subdev *subdev,
			       struct v4l2_subdev_state *state,
			       struct v4l2_subdev_mbus_code_enum *code)
{
	struct xtpg_device *xtpg = to_tpg(subdev);

	/*
	 * In two pads mode the source pad format is always identical to the
	 * sink pad format, only report the format currently configured.
	 */
	if (xtpg->npads == 2 && code->pad == 1) {
		if (code->index)
			return -EINVAL;

		code->code = v4l2_subdev_state_get_format(state, 1)->code;

		return 0;
	}

	if (code->index >= ARRAY_SIZE(xtpg_formats))
		return -EINVAL;

	code->code = xtpg_formats[code->index].code;

	return 0;
}

static int xtpg_enum_frame_size(struct v4l2_subdev *subdev,
				struct v4l2_subdev_state *state,
				struct v4l2_subdev_frame_size_enum *fse)
{
	struct xtpg_device *xtpg = to_tpg(subdev);

	if (fse->index)
		return -EINVAL;

	/*
	 * In two pads mode the source pad format is always identical to the
	 * sink pad format, the frame size can't be changed on the source pad.
	 */
	if (xtpg->npads == 2 && fse->pad == 1) {
		const struct v4l2_mbus_framefmt *format;

		format = v4l2_subdev_state_get_format(state, 1);
		if (fse->code != format->code)
			return -EINVAL;

		fse->min_width = format->width;
		fse->max_width = format->width;
		fse->min_height = format->height;
		fse->max_height = format->height;

		return 0;
	}

	if (!xtpg_get_format(fse->code))
		return -EINVAL;

	fse->min_width = XTPG_MIN_WIDTH;
	fse->max_width = xtpg->max_width;
	fse->min_height = XTPG_MIN_HEIGHT;
	fse->max_height = xtpg->max_height;

	return 0;
}

static int xtpg_set_format(struct v4l2_subdev *subdev,
			   struct v4l2_subdev_state *state,
			   struct v4l2_subdev_format *fmt)
{
	struct xtpg_device *xtpg = to_tpg(subdev);
	struct v4l2_mbus_framefmt *format;

	/*
	 * In two pads mode the source pad format is always identical to the
	 * sink pad format.
	 */
	if (xtpg->npads == 2 && fmt->pad == 1) {
		fmt->format = *v4l2_subdev_state_get_format(state, 1);
		return 0;
	}

	format = v4l2_subdev_state_get_format(state, 0);

	if (xtpg_get_format(fmt->format.code))
		format->code = fmt->format.code;
	else
		format->code = xtpg->default_format.code;

	format->width = clamp_t(unsigned int, fmt->format.width,
				XTPG_MIN_WIDTH, xtpg->max_width);
	format->height = clamp_t(unsigned int, fmt->format.height,
				 XTPG_MIN_HEIGHT, xtpg->max_height);

	fmt->format = *format;

	/* Propagate the format to the source pad. */
	if (xtpg->npads == 2)
		*v4l2_subdev_state_get_format(state, 1) = *format;

	return 0;
}

/* -----------------------------------------------------------------------------
 * V4L2 Subdevice Internal Operations
 */

static int xtpg_init_state(struct v4l2_subdev *subdev,
			   struct v4l2_subdev_state *state)
{
	struct xtpg_device *xtpg = to_tpg(subdev);
	unsigned int i;

	for (i = 0; i < xtpg->npads; ++i)
		*v4l2_subdev_state_get_format(state, i) = xtpg->default_format;

	return 0;
}

/* -----------------------------------------------------------------------------
 * V4L2 Controls
 */

static int xtpg_s_ctrl(struct v4l2_ctrl *ctrl)
{
	struct xtpg_device *xtpg = container_of(ctrl->handler,
						struct xtpg_device,
						ctrl_handler);

	switch (ctrl->id) {
	case V4L2_CID_TEST_PATTERN:
		xtpg_write(xtpg, XTPG_HLS_BG_PATTERN, ctrl->val);
		return 0;
	case V4L2_CID_XILINX_TPG_HLS_FG_PATTERN:
		xtpg_write(xtpg, XTPG_HLS_FG_PATTERN, ctrl->val);
		return 0;
	case V4L2_CID_XILINX_TPG_COLOR_MASK:
		xtpg_write(xtpg, XTPG_HLS_MASK_ID, ctrl->val);
		return 0;
	case V4L2_CID_XILINX_TPG_MOTION_SPEED:
		xtpg_write(xtpg, XTPG_HLS_MOTION_SPEED, ctrl->val);
		return 0;
	case V4L2_CID_XILINX_TPG_CROSS_HAIR_ROW:
		xtpg_write(xtpg, XTPG_HLS_CROSS_HAIR_HOR, ctrl->val);
		return 0;
	case V4L2_CID_XILINX_TPG_CROSS_HAIR_COLUMN:
		xtpg_write(xtpg, XTPG_HLS_CROSS_HAIR_VER, ctrl->val);
		return 0;
	case V4L2_CID_XILINX_TPG_ZPLATE_HOR_START:
		xtpg_write(xtpg, XTPG_HLS_ZPLATE_HOR_CNTL_START, ctrl->val);
		return 0;
	case V4L2_CID_XILINX_TPG_ZPLATE_HOR_SPEED:
		xtpg_write(xtpg, XTPG_HLS_ZPLATE_HOR_CNTL_DELTA, ctrl->val);
		return 0;
	case V4L2_CID_XILINX_TPG_ZPLATE_VER_START:
		xtpg_write(xtpg, XTPG_HLS_ZPLATE_VER_CNTL_START, ctrl->val);
		return 0;
	case V4L2_CID_XILINX_TPG_ZPLATE_VER_SPEED:
		xtpg_write(xtpg, XTPG_HLS_ZPLATE_VER_CNTL_DELTA, ctrl->val);
		return 0;
	case V4L2_CID_XILINX_TPG_BOX_SIZE:
		xtpg_write(xtpg, XTPG_HLS_BOX_SIZE, ctrl->val);
		return 0;
	case V4L2_CID_XILINX_TPG_BOX_COLOR:
		xtpg_write(xtpg, XTPG_HLS_BOX_COLOR_RED_CB, ctrl->val >> 16);
		xtpg_write(xtpg, XTPG_HLS_BOX_COLOR_GREEN_CR, ctrl->val >> 8);
		xtpg_write(xtpg, XTPG_HLS_BOX_COLOR_BLUE_Y, ctrl->val);
		return 0;
	}

	return 0;
}

static const struct v4l2_ctrl_ops xtpg_ctrl_ops = {
	.s_ctrl	= xtpg_s_ctrl,
};

static const char *const xtpg_pattern_strings[] = {
	"Passthrough",
	"Horizontal Ramp",
	"Vertical Ramp",
	"Temporal Ramp",
	"Solid Red",
	"Solid Green",
	"Solid Blue",
	"Solid Black",
	"Solid White",
	"Color Bars",
	"Zone Plate",
	"Tartan Color Bars",
	"Cross Hatch",
	"Color Sweep",
	"Vertical/Horizontal Ramps",
	"Black/White Checker Board",
	"PseudoRandom",
};

static const char *const xtpg_fg_pattern_strings[] = {
	"No Overlay",
	"Moving Box",
	"Cross Hairs",
};

static const struct v4l2_ctrl_config xtpg_ctrls[] = {
	{
		.ops	= &xtpg_ctrl_ops,
		.id	= V4L2_CID_XILINX_TPG_HLS_FG_PATTERN,
		.name	= "Test Pattern: Foreground Pattern",
		.type	= V4L2_CTRL_TYPE_MENU,
		.min	= 0,
		.max	= ARRAY_SIZE(xtpg_fg_pattern_strings) - 1,
		.qmenu	= xtpg_fg_pattern_strings,
	}, {
		.ops	= &xtpg_ctrl_ops,
		.id	= V4L2_CID_XILINX_TPG_COLOR_MASK,
		.name	= "Test Pattern: Color Mask",
		.type	= V4L2_CTRL_TYPE_BITMASK,
		.min	= 0,
		.max	= 0x7,
		.def	= 0,
	}, {
		.ops	= &xtpg_ctrl_ops,
		.id	= V4L2_CID_XILINX_TPG_MOTION_SPEED,
		.name	= "Test Pattern: Motion Speed",
		.type	= V4L2_CTRL_TYPE_INTEGER,
		.min	= 0,
		.max	= (1 << 8) - 1,
		.step	= 1,
		.def	= 4,
		.flags	= V4L2_CTRL_FLAG_SLIDER,
	}, {
		.ops	= &xtpg_ctrl_ops,
		.id	= V4L2_CID_XILINX_TPG_CROSS_HAIR_ROW,
		.name	= "Test Pattern: Cross Hairs Row",
		.type	= V4L2_CTRL_TYPE_INTEGER,
		.min	= 0,
		.max	= (1 << 12) - 1,
		.step	= 1,
		.def	= 0x64,
		.flags	= V4L2_CTRL_FLAG_SLIDER,
	}, {
		.ops	= &xtpg_ctrl_ops,
		.id	= V4L2_CID_XILINX_TPG_CROSS_HAIR_COLUMN,
		.name	= "Test Pattern: Cross Hairs Column",
		.type	= V4L2_CTRL_TYPE_INTEGER,
		.min	= 0,
		.max	= (1 << 12) - 1,
		.step	= 1,
		.def	= 0x64,
		.flags	= V4L2_CTRL_FLAG_SLIDER,
	}, {
		.ops	= &xtpg_ctrl_ops,
		.id	= V4L2_CID_XILINX_TPG_ZPLATE_HOR_START,
		.name	= "Test Pattern: Zplate Horizontal Start Pos",
		.type	= V4L2_CTRL_TYPE_INTEGER,
		.min	= 0,
		.max	= (1 << 16) - 1,
		.step	= 1,
		.def	= 0x1e,
		.flags	= V4L2_CTRL_FLAG_SLIDER,
	}, {
		.ops	= &xtpg_ctrl_ops,
		.id	= V4L2_CID_XILINX_TPG_ZPLATE_HOR_SPEED,
		.name	= "Test Pattern: Zplate Horizontal Speed",
		.type	= V4L2_CTRL_TYPE_INTEGER,
		.min	= 0,
		.max	= (1 << 16) - 1,
		.step	= 1,
		.def	= 0,
		.flags	= V4L2_CTRL_FLAG_SLIDER,
	}, {
		.ops	= &xtpg_ctrl_ops,
		.id	= V4L2_CID_XILINX_TPG_ZPLATE_VER_START,
		.name	= "Test Pattern: Zplate Vertical Start Pos",
		.type	= V4L2_CTRL_TYPE_INTEGER,
		.min	= 0,
		.max	= (1 << 16) - 1,
		.step	= 1,
		.def	= 1,
		.flags	= V4L2_CTRL_FLAG_SLIDER,
	}, {
		.ops	= &xtpg_ctrl_ops,
		.id	= V4L2_CID_XILINX_TPG_ZPLATE_VER_SPEED,
		.name	= "Test Pattern: Zplate Vertical Speed",
		.type	= V4L2_CTRL_TYPE_INTEGER,
		.min	= 0,
		.max	= (1 << 16) - 1,
		.step	= 1,
		.def	= 0,
		.flags	= V4L2_CTRL_FLAG_SLIDER,
	}, {
		.ops	= &xtpg_ctrl_ops,
		.id	= V4L2_CID_XILINX_TPG_BOX_SIZE,
		.name	= "Test Pattern: Box Size",
		.type	= V4L2_CTRL_TYPE_INTEGER,
		.min	= 0,
		.max	= (1 << 12) - 1,
		.step	= 1,
		.def	= 0x32,
		.flags	= V4L2_CTRL_FLAG_SLIDER,
	}, {
		.ops	= &xtpg_ctrl_ops,
		.id	= V4L2_CID_XILINX_TPG_BOX_COLOR,
		.name	= "Test Pattern: Box Color(RGB/YCbCr)",
		.type	= V4L2_CTRL_TYPE_INTEGER,
		.min	= 0,
		.max	= (1 << 24) - 1,
		.step	= 1,
		.def	= 0,
	},
};

/* -----------------------------------------------------------------------------
 * V4L2 Subdevice Operations
 */

static const struct v4l2_subdev_video_ops xtpg_video_ops = {
	.s_stream = v4l2_subdev_s_stream_helper,
};

static const struct v4l2_subdev_pad_ops xtpg_pad_ops = {
	.enum_mbus_code		= xtpg_enum_mbus_code,
	.enum_frame_size	= xtpg_enum_frame_size,
	.get_fmt		= v4l2_subdev_get_fmt,
	.set_fmt		= xtpg_set_format,
	.enable_streams		= xtpg_enable_streams,
	.disable_streams	= xtpg_disable_streams,
};

static const struct v4l2_subdev_ops xtpg_ops = {
	.video  = &xtpg_video_ops,
	.pad    = &xtpg_pad_ops,
};

static const struct v4l2_subdev_internal_ops xtpg_internal_ops = {
	.init_state = xtpg_init_state,
};

/* -----------------------------------------------------------------------------
 * Media Operations
 */

static const struct media_entity_operations xtpg_media_ops = {
	.get_fwnode_pad = v4l2_subdev_get_fwnode_pad_1_to_1,
	.link_validate = v4l2_subdev_link_validate,
};

/* -----------------------------------------------------------------------------
 * Power Management
 */

static int xtpg_pm_suspend(struct device *dev)
{
	struct xtpg_device *xtpg = dev_get_drvdata(dev);

	xtpg->saved_ctrl = xtpg_read(xtpg, XTPG_HLS_CTRL);
	xtpg_stop(xtpg);

	return 0;
}

static int xtpg_pm_resume(struct device *dev)
{
	struct xtpg_device *xtpg = dev_get_drvdata(dev);

	if (xtpg->saved_ctrl & XTPG_HLS_CTRL_AUTO_RESTART)
		xtpg_start(xtpg);

	return 0;
}

static DEFINE_SIMPLE_DEV_PM_OPS(xtpg_pm_ops, xtpg_pm_suspend, xtpg_pm_resume);

/* -----------------------------------------------------------------------------
 * Platform Device Driver
 */

static int xtpg_parse_of(struct xtpg_device *xtpg)
{
	struct device *dev = xtpg->dev;
	struct device_node *node = dev->of_node;
	unsigned int nports = 0;
	bool has_endpoint = false;
	int ret;

	ret = of_property_read_u32(node, "xlnx,max-width", &xtpg->max_width);
	if (ret < 0) {
		dev_err(dev, "missing xlnx,max-width property\n");
		return ret;
	}

	if (xtpg->max_width < XTPG_MIN_WIDTH ||
	    xtpg->max_width > XTPG_MAX_WIDTH) {
		dev_err(dev, "invalid xlnx,max-width value %u\n",
			xtpg->max_width);
		return -EINVAL;
	}

	ret = of_property_read_u32(node, "xlnx,max-height", &xtpg->max_height);
	if (ret < 0) {
		dev_err(dev, "missing xlnx,max-height property\n");
		return ret;
	}

	if (xtpg->max_height < XTPG_MIN_HEIGHT ||
	    xtpg->max_height > XTPG_MAX_HEIGHT) {
		dev_err(dev, "invalid xlnx,max-height value %u\n",
			xtpg->max_height);
		return -EINVAL;
	}

	ret = of_property_read_u32(node, "xlnx,ppc", &xtpg->ppc);
	if (ret < 0) {
		xtpg->ppc = XTPG_DEF_PPC;
	} else if (xtpg->ppc != 1 && xtpg->ppc != 2 && xtpg->ppc != 4 &&
		   xtpg->ppc != 8) {
		dev_err(dev, "invalid xlnx,ppc value %u\n", xtpg->ppc);
		return -EINVAL;
	}

	for_each_of_graph_port(node, port) {
		/* The TPG has an input if its first port has an endpoint. */
		if (nports == 0) {
			struct device_node *endpoint;

			endpoint = of_graph_get_next_port_endpoint(port, NULL);
			if (endpoint)
				has_endpoint = true;
			of_node_put(endpoint);
		}

		/* Count the number of ports. */
		nports++;
	}

	if (nports != 1 && nports != 2) {
		dev_err(dev, "invalid number of ports %u\n", nports);
		return -EINVAL;
	}

	xtpg->npads = nports;
	if (nports == 2 && has_endpoint)
		xtpg->has_input = true;

	return 0;
}

static int xtpg_notify_bound(struct v4l2_async_notifier *notifier,
			     struct v4l2_subdev *sd,
			     struct v4l2_async_connection *asc)
{
	struct xtpg_device *xtpg =
		container_of(notifier, struct xtpg_device, notifier);

	return v4l2_create_fwnode_links_to_pad(sd, &xtpg->pads[0],
					       MEDIA_LNK_FL_ENABLED |
					       MEDIA_LNK_FL_IMMUTABLE);
}

static const struct v4l2_async_notifier_operations xtpg_notify_ops = {
	.bound = xtpg_notify_bound,
};

static int xtpg_register_notifier(struct xtpg_device *xtpg)
{
	struct v4l2_async_connection *asc;
	struct fwnode_handle *ep;
	int ret;

	/* Port 0 is the sink port only when the TPG has an input port. */
	if (xtpg->npads != 2)
		return 0;

	ep = fwnode_graph_get_endpoint_by_id(dev_fwnode(xtpg->dev), 0, 0,
					     FWNODE_GRAPH_ENDPOINT_NEXT);
	if (!ep)
		return 0;

	v4l2_async_subdev_nf_init(&xtpg->notifier, &xtpg->subdev);
	xtpg->notifier.ops = &xtpg_notify_ops;

	asc = v4l2_async_nf_add_fwnode_remote(&xtpg->notifier, ep,
					      struct v4l2_async_connection);
	fwnode_handle_put(ep);
	if (IS_ERR(asc)) {
		v4l2_async_nf_cleanup(&xtpg->notifier);
		return PTR_ERR(asc);
	}

	ret = v4l2_async_nf_register(&xtpg->notifier);
	if (ret)
		v4l2_async_nf_cleanup(&xtpg->notifier);

	return ret;
}

static int xtpg_probe(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct v4l2_subdev *subdev;
	struct xtpg_device *xtpg;
	unsigned int i;
	int ret;

	xtpg = devm_kzalloc(dev, sizeof(*xtpg), GFP_KERNEL);
	if (!xtpg)
		return -ENOMEM;

	xtpg->dev = dev;

	ret = xtpg_parse_of(xtpg);
	if (ret < 0)
		return ret;

	xtpg->iomem = devm_platform_ioremap_resource(pdev, 0);
	if (IS_ERR(xtpg->iomem))
		return PTR_ERR(xtpg->iomem);

	xtpg->clk = devm_clk_get_enabled(dev, NULL);
	if (IS_ERR(xtpg->clk))
		return dev_err_probe(dev, PTR_ERR(xtpg->clk),
				     "failed to get core clock\n");

	xtpg->vtmux_gpio = devm_gpiod_get_optional(dev, "timing",
						   GPIOD_OUT_HIGH);
	if (IS_ERR(xtpg->vtmux_gpio))
		return dev_err_probe(dev, PTR_ERR(xtpg->vtmux_gpio),
				     "failed to get timing mux GPIO\n");

	xtpg->rst_gpio = devm_gpiod_get_optional(dev, "reset", GPIOD_OUT_HIGH);
	if (IS_ERR(xtpg->rst_gpio))
		return dev_err_probe(dev, PTR_ERR(xtpg->rst_gpio),
				     "failed to get reset GPIO\n");

	xtpg->vtc = xvtc_of_get(dev->of_node);
	if (IS_ERR(xtpg->vtc))
		return dev_err_probe(dev, PTR_ERR(xtpg->vtc),
				     "failed to get VTC\n");

	/* Release the reset. */
	gpiod_set_value_cansleep(xtpg->rst_gpio, 0);

	/*
	 * Initialize the media pads. Pad numbers depend on the number of pads:
	 * the single pad of a TPG without an input is a source pad, while a TPG
	 * with an input has a sink pad followed by a source pad.
	 */
	if (xtpg->npads == 2) {
		xtpg->pads[0].flags = MEDIA_PAD_FL_SINK;
		xtpg->pads[1].flags = MEDIA_PAD_FL_SOURCE;
	} else {
		xtpg->pads[0].flags = MEDIA_PAD_FL_SOURCE;
	}

	/* Initialize the default format. */
	xtpg->default_format.code = xtpg_formats[0].code;
	xtpg->default_format.field = V4L2_FIELD_NONE;
	xtpg->default_format.colorspace = V4L2_COLORSPACE_SRGB;
	xtpg->default_format.width = min_t(u32, XTPG_DEF_WIDTH,
					   xtpg->max_width);
	xtpg->default_format.height = min_t(u32, XTPG_DEF_HEIGHT,
					    xtpg->max_height);

	/* Initialize V4L2 subdevice and media entity. */
	subdev = &xtpg->subdev;
	v4l2_subdev_init(subdev, &xtpg_ops);
	subdev->internal_ops = &xtpg_internal_ops;
	subdev->dev = dev;
	strscpy(subdev->name, dev_name(dev), sizeof(subdev->name));
	v4l2_set_subdevdata(subdev, xtpg);
	subdev->flags |= V4L2_SUBDEV_FL_HAS_DEVNODE;
	subdev->entity.ops = &xtpg_media_ops;

	ret = media_entity_pads_init(&subdev->entity, xtpg->npads, xtpg->pads);
	if (ret < 0)
		return ret;

	v4l2_ctrl_handler_init(&xtpg->ctrl_handler, 3 + ARRAY_SIZE(xtpg_ctrls));

	xtpg->vblank = v4l2_ctrl_new_std(&xtpg->ctrl_handler, &xtpg_ctrl_ops,
					 V4L2_CID_VBLANK, XTPG_MIN_VBLANK,
					 XTPG_MAX_VBLANK, 1, 100);
	xtpg->hblank = v4l2_ctrl_new_std(&xtpg->ctrl_handler, &xtpg_ctrl_ops,
					 V4L2_CID_HBLANK, XTPG_MIN_HBLANK,
					 XTPG_MAX_HBLANK, 1, 100);
	xtpg->pattern =
		v4l2_ctrl_new_std_menu_items(&xtpg->ctrl_handler,
					     &xtpg_ctrl_ops,
					     V4L2_CID_TEST_PATTERN,
					     ARRAY_SIZE(xtpg_pattern_strings) - 1,
					     1, 9, xtpg_pattern_strings);

	for (i = 0; i < ARRAY_SIZE(xtpg_ctrls); i++)
		v4l2_ctrl_new_custom(&xtpg->ctrl_handler, &xtpg_ctrls[i], NULL);

	if (xtpg->ctrl_handler.error) {
		ret = xtpg->ctrl_handler.error;
		dev_err(dev, "failed to add controls\n");
		goto error_ctrl;
	}

	subdev->ctrl_handler = &xtpg->ctrl_handler;

	/*
	 * The subdev state is protected by the control handler lock, as the
	 * stream start and stop operations access controls.
	 */
	subdev->state_lock = subdev->ctrl_handler->lock;

	ret = v4l2_subdev_init_finalize(subdev);
	if (ret < 0)
		goto error_ctrl;

	xtpg_update_pattern_control(xtpg, true, true);

	ret = v4l2_ctrl_handler_setup(&xtpg->ctrl_handler);
	if (ret < 0) {
		dev_err(dev, "failed to set controls\n");
		goto error_subdev;
	}

	platform_set_drvdata(pdev, xtpg);

	ret = xtpg_register_notifier(xtpg);
	if (ret < 0)
		goto error_subdev;

	ret = v4l2_async_register_subdev(subdev);
	if (ret < 0) {
		dev_err(dev, "failed to register subdev\n");
		goto error_notifier;
	}

	return 0;

error_notifier:
	v4l2_async_nf_unregister(&xtpg->notifier);
	v4l2_async_nf_cleanup(&xtpg->notifier);
error_subdev:
	v4l2_subdev_cleanup(subdev);
error_ctrl:
	v4l2_ctrl_handler_free(&xtpg->ctrl_handler);
	media_entity_cleanup(&subdev->entity);
	xvtc_put(xtpg->vtc);
	return ret;
}

static void xtpg_remove(struct platform_device *pdev)
{
	struct xtpg_device *xtpg = platform_get_drvdata(pdev);
	struct v4l2_subdev *subdev = &xtpg->subdev;

	v4l2_async_nf_unregister(&xtpg->notifier);
	v4l2_async_nf_cleanup(&xtpg->notifier);
	v4l2_async_unregister_subdev(subdev);
	v4l2_subdev_cleanup(subdev);
	v4l2_ctrl_handler_free(&xtpg->ctrl_handler);
	media_entity_cleanup(&subdev->entity);
	xvtc_put(xtpg->vtc);
}

static const struct of_device_id xtpg_of_id_table[] = {
	{ .compatible = "xlnx,v-tpg-8.0" },
	{ }
};
MODULE_DEVICE_TABLE(of, xtpg_of_id_table);

static struct platform_driver xtpg_driver = {
	.driver = {
		.name		= "xilinx-hls-tpg",
		.pm		= pm_sleep_ptr(&xtpg_pm_ops),
		.of_match_table	= xtpg_of_id_table,
	},
	.probe			= xtpg_probe,
	.remove			= xtpg_remove,
};

module_platform_driver(xtpg_driver);

MODULE_AUTHOR("Tomi Valkeinen <tomi.valkeinen@ideasonboard.com>");
MODULE_DESCRIPTION("Xilinx HLS Test Pattern Generator Driver");
MODULE_LICENSE("GPL");
